from __future__ import annotations

from typing import Protocol

from app.jobs.models import Job, JobStatus


class JobRepository(Protocol):
    def create(self, job_id: str, url: str) -> Job: ...

    def get(self, job_id: str) -> Job | None: ...

    def update_status(self, job_id: str, status: JobStatus, progress: float | None = None) -> None: ...

    def set_error(self, job_id: str, error: str) -> None: ...

    def set_result(self, job_id: str, result: object) -> None: ...

    def remove(self, job_id: str, video_id: str | None = None) -> None: ...

    def get_cached_job_id(self, video_id: str) -> str | None: ...

    def set_cache(self, video_id: str, job_id: str) -> None: ...

    def get_audio_cache(self, video_id: str) -> tuple[str, str, float] | None: ...

    def set_audio_cache(self, video_id: str, audio_path: str, title: str, duration: float) -> None: ...

    def cleanup_old(self, max_age_seconds: float = 3600) -> list[str]: ...

    @property
    def active_count(self) -> int: ...
